name: Unity Build & Release

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Build Directory
      - name: Prepare Build Environment
        run: |
          mkdir -p "Soul-Shot/Builds/Windows"

      # Cache Library Folder
      - name: Cache Library Folder
        uses: actions/cache@v3
        with:
          path: "Soul-Shot/Library"
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-

      # Build Unity Project
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: "Soul-Shot"
          targetPlatform: StandaloneWindows64
          buildName: "Windows"
          buildsPath: "Builds"  # Now goes to Soul-Shot/Builds/Windows

      # Verify Build Output
      - name: Verify Build Files
        run: |
          echo "Build artifacts:"
          ls -la "Soul-Shot/Builds/Windows"
          [ -f "Soul-Shot/Builds/Windows/SoulShot.exe" ] || exit 1

      # Compress Build Artifacts
      - name: Create Build Archive
        run: |
          cd "Soul-Shot/Builds"
          zip -r ../game-build-${{ github.run_number }}.zip Windows/*
          echo "BUILD_ZIP=game-build-${{ github.run_number }}.zip" >> $GITHUB_ENV

      # Upload Artifact (temporary storage between jobs)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-build
          path: Soul-Shot/game-build-${{ github.run_number }}.zip
          retention-days: 1

      # Version Management (using GameVersion.txt)
      - name: Update Game Version
        id: version
        run: |
          mkdir -p "Soul-Shot/Assets/Resources"
          GAME_VERSION_FILE="Soul-Shot/Assets/Resources/GameVersion.txt"
          [ -f "$GAME_VERSION_FILE" ] || echo "1.0.0" > "$GAME_VERSION_FILE"
          CURRENT_VERSION=$(cat "$GAME_VERSION_FILE")
          NEW_VERSION=$(echo "$CURRENT_VERSION" | awk -F. -v OFS=. '{
            if(NF==3){$3+=1}  # Major.Minor.Patch
            print $0
          }')
          echo "$NEW_VERSION" > "$GAME_VERSION_FILE"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_TAG=v$NEW_VERSION" >> $GITHUB_ENV
          echo "Updated game version from $CURRENT_VERSION to $NEW_VERSION"

      # Commit Version Update
      - name: Commit Version Change
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add "Soul-Shot/Assets/Resources/GameVersion.txt"
          git commit -m "[CI] Update version to ${{ steps.version.outputs.NEW_VERSION }}"
          git push origin main

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download the zipped build
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: game-build
          path: release-files

      # Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: "SoulShot ${{ env.VERSION_TAG }}"
          body: |
            Automatic build for commit ${{ github.sha }}
            Build Number: ${{ github.run_number }}
          files: release-files/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
